### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by GrahamCampbell** [toin0u/DigitalOceanV2#29]
I see you're using `PHP_INT_MAX` for digital ocean's "per page" value in pagination. I don't think they will support a number that large, and even if they did, we'd likely run out of memory on our server trying to deal with a dataset that large all at once.

**Comment by jpg5f2** [comment]
I see it is using a static 200 now, but the actual page is not being specific, limiting users to 200 droplets.  Should a page parameter be added to droplet getAll?

**Comment by Teevio** [comment]
Does this issue apply anymore?  The `$per_page` and `$page` variables exist for the getAll function.

**Comment by GrahamCampbell** [comment]
The issue was rather about automatic pagination, so we could get all, and then the library would iterate over all the pages for us.

**Comment by cam-vanorman** [comment]
This issue appears to still be under discussion, so I thought I'd add some more info.

When querying `https://api.digitalocean.com/v2/droplets`, the DigitalOcean API returns a `meta` key with `total` number of droplets.

![Screen Shot 2019-10-03 at 6 34 33 PM](https://user-images.githubusercontent.com/5124234/66174970-8365e580-e60c-11e9-995c-7e539239ed3b.png)


Retaining this meta value at the end of the `getAll()` request would make paginating the API much easier with this library and the package @GrahamCampbell developed (https://github.com/GrahamCampbell/Laravel-DigitalOcean).

If anyone has suggestions for paginating the API rather than setting a high `$per_page` variable, I'm all 👂.
